import Header from "@/components/layout/header";
import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jetbrains",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr" className={`${jetbrains.variable} antialiased`}>
      <body className="font-mono">
        <Header />
        <main className="min-h-screen bg-gray-50">
          <div className="container px-4 py-8 max-w-7xl">{children}</div>
        </main>
      </body>
    </html>
  );
}
