import Header from "@/components/layout/header";
import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jetbrains",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${jetbrains.variable}`}>
      <body className="font-mono">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <Header />
          <main className="min-h-screen bg-gray-50 dark:bg-[#0d1117]">
            <div className="container px-4 py-8 max-w-7xl">{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
